# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\ProyectoSullana\proyecto_sullana_escritorio\View\inicioSistema.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("background-color: rgb(254, 182, 26);\n"
"border-radius: 7px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTituloPrincipal = QtWidgets.QLabel(self.centralwidget)
        self.lblTituloPrincipal.setGeometry(QtCore.QRect(535, 100, 850, 250))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.lblTituloPrincipal.setFont(font)
        self.lblTituloPrincipal.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lblTituloPrincipal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTituloPrincipal.setWordWrap(True)
        self.lblTituloPrincipal.setObjectName("lblTituloPrincipal")
        self.imgVentaBeneficiado = QtWidgets.QLabel(self.centralwidget)
        self.imgVentaBeneficiado.setGeometry(QtCore.QRect(625, 446, 300, 300))
        self.imgVentaBeneficiado.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border: 2px solid black;\n"
"border-radius: 15px;")
        self.imgVentaBeneficiado.setText("")
        self.imgVentaBeneficiado.setScaledContents(True)
        self.imgVentaBeneficiado.setWordWrap(True)
        self.imgVentaBeneficiado.setObjectName("imgVentaBeneficiado")
        self.lblVenta = QtWidgets.QLabel(self.centralwidget)
        self.lblVenta.setGeometry(QtCore.QRect(620, 766, 311, 111))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lblVenta.setFont(font)
        self.lblVenta.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lblVenta.setAlignment(QtCore.Qt.AlignCenter)
        self.lblVenta.setObjectName("lblVenta")
        self.lblSubTituloPrincipal = QtWidgets.QLabel(self.centralwidget)
        self.lblSubTituloPrincipal.setGeometry(QtCore.QRect(535, 350, 850, 60))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lblSubTituloPrincipal.setFont(font)
        self.lblSubTituloPrincipal.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
" letter-spacing: 2px;\n"
"")
        self.lblSubTituloPrincipal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSubTituloPrincipal.setIndent(-1)
        self.lblSubTituloPrincipal.setObjectName("lblSubTituloPrincipal")
        self.lblmimizar = QtWidgets.QLabel(self.centralwidget)
        self.lblmimizar.setGeometry(QtCore.QRect(1840, 10, 30, 30))
        self.lblmimizar.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lblmimizar.setText("")
        self.lblmimizar.setScaledContents(True)
        self.lblmimizar.setWordWrap(False)
        self.lblmimizar.setObjectName("lblmimizar")
        self.lblcerrar = QtWidgets.QLabel(self.centralwidget)
        self.lblcerrar.setGeometry(QtCore.QRect(1880, 10, 30, 30))
        self.lblcerrar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblcerrar.setAutoFillBackground(False)
        self.lblcerrar.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lblcerrar.setText("")
        self.lblcerrar.setScaledContents(True)
        self.lblcerrar.setAlignment(QtCore.Qt.AlignCenter)
        self.lblcerrar.setWordWrap(False)
        self.lblcerrar.setIndent(-1)
        self.lblcerrar.setObjectName("lblcerrar")
        self.btnminimizar = QtWidgets.QPushButton(self.centralwidget)
        self.btnminimizar.setGeometry(QtCore.QRect(1840, 10, 30, 30))
        self.btnminimizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnminimizar.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.btnminimizar.setText("")
        self.btnminimizar.setObjectName("btnminimizar")
        self.btnCerrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCerrar.setGeometry(QtCore.QRect(1880, 10, 30, 30))
        self.btnCerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCerrar.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.btnCerrar.setText("")
        self.btnCerrar.setObjectName("btnCerrar")
        self.imgVentaVivo = QtWidgets.QLabel(self.centralwidget)
        self.imgVentaVivo.setGeometry(QtCore.QRect(1010, 446, 300, 300))
        self.imgVentaVivo.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border: 2px solid black;\n"
"border-radius: 15px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.imgVentaVivo.setText("")
        self.imgVentaVivo.setScaledContents(True)
        self.imgVentaVivo.setWordWrap(True)
        self.imgVentaVivo.setObjectName("imgVentaVivo")
        self.lblVenta_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblVenta_2.setGeometry(QtCore.QRect(1009, 766, 301, 111))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lblVenta_2.setFont(font)
        self.lblVenta_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lblVenta_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblVenta_2.setObjectName("lblVenta_2")
        self.btnUnidadMantenimiento = QtWidgets.QPushButton(self.centralwidget)
        self.btnUnidadMantenimiento.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.btnUnidadMantenimiento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnUnidadMantenimiento.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.btnUnidadMantenimiento.setText("")
        self.btnUnidadMantenimiento.setObjectName("btnUnidadMantenimiento")
        self.img_unidad_mantenimiento = QtWidgets.QLabel(self.centralwidget)
        self.img_unidad_mantenimiento.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.img_unidad_mantenimiento.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.img_unidad_mantenimiento.setText("")
        self.img_unidad_mantenimiento.setScaledContents(True)
        self.img_unidad_mantenimiento.setObjectName("img_unidad_mantenimiento")
        self.frmSombra = QtWidgets.QFrame(self.centralwidget)
        self.frmSombra.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.frmSombra.setStyleSheet("background-color: rgba(0, 0, 0, 80);\n"
"border-radius: 0px;")
        self.frmSombra.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmSombra.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmSombra.setObjectName("frmSombra")
        self.frmIngresarPassword = QtWidgets.QFrame(self.centralwidget)
        self.frmIngresarPassword.setGeometry(QtCore.QRect(730, 420, 550, 300))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frmIngresarPassword.setFont(font)
        self.frmIngresarPassword.setStyleSheet("#frmIngresarPassword{background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-radius: 10px;\n"
"border: 2px solid #D9D9D9;}")
        self.frmIngresarPassword.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmIngresarPassword.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmIngresarPassword.setObjectName("frmIngresarPassword")
        self.lblTextoUnidadMantenimiento = QtWidgets.QLabel(self.frmIngresarPassword)
        self.lblTextoUnidadMantenimiento.setGeometry(QtCore.QRect(50, 35, 450, 71))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblTextoUnidadMantenimiento.setFont(font)
        self.lblTextoUnidadMantenimiento.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblTextoUnidadMantenimiento.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTextoUnidadMantenimiento.setObjectName("lblTextoUnidadMantenimiento")
        self.txtPasswordUnidadMantenimiento = QtWidgets.QLineEdit(self.frmIngresarPassword)
        self.txtPasswordUnidadMantenimiento.setGeometry(QtCore.QRect(75, 140, 400, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtPasswordUnidadMantenimiento.setFont(font)
        self.txtPasswordUnidadMantenimiento.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border: 2px solid #000;\n"
"padding: 5px")
        self.txtPasswordUnidadMantenimiento.setText("")
        self.txtPasswordUnidadMantenimiento.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPasswordUnidadMantenimiento.setAlignment(QtCore.Qt.AlignCenter)
        self.txtPasswordUnidadMantenimiento.setObjectName("txtPasswordUnidadMantenimiento")
        self.btnAceptarFrmIngresarPassword = QtWidgets.QPushButton(self.frmIngresarPassword)
        self.btnAceptarFrmIngresarPassword.setGeometry(QtCore.QRect(90, 215, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnAceptarFrmIngresarPassword.setFont(font)
        self.btnAceptarFrmIngresarPassword.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAceptarFrmIngresarPassword.setStyleSheet("background-color: rgb(36, 211, 21);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius: 5px;")
        self.btnAceptarFrmIngresarPassword.setFlat(False)
        self.btnAceptarFrmIngresarPassword.setObjectName("btnAceptarFrmIngresarPassword")
        self.btnCancelarFrmIngresarPassword = QtWidgets.QPushButton(self.frmIngresarPassword)
        self.btnCancelarFrmIngresarPassword.setGeometry(QtCore.QRect(310, 215, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnCancelarFrmIngresarPassword.setFont(font)
        self.btnCancelarFrmIngresarPassword.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCancelarFrmIngresarPassword.setStyleSheet("background-color: rgb(234, 29, 49);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius: 5px;")
        self.btnCancelarFrmIngresarPassword.setObjectName("btnCancelarFrmIngresarPassword")
        self.frame_4 = QtWidgets.QFrame(self.frmIngresarPassword)
        self.frame_4.setGeometry(QtCore.QRect(50, 110, 450, 3))
        self.frame_4.setStyleSheet("background-color: rgb(139, 139, 139);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.imgFondo = QtWidgets.QLabel(self.centralwidget)
        self.imgFondo.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.imgFondo.setText("")
        self.imgFondo.setScaledContents(True)
        self.imgFondo.setAlignment(QtCore.Qt.AlignCenter)
        self.imgFondo.setObjectName("imgFondo")
        self.frmPrestamoCubetasJabas = QtWidgets.QFrame(self.centralwidget)
        self.frmPrestamoCubetasJabas.setGeometry(QtCore.QRect(460, 215, 1000, 650))
        self.frmPrestamoCubetasJabas.setStyleSheet("#frmPrestamoCubetasJabas{background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-radius: 10px;\n"
"border: 2px solid #D9D9D9;}")
        self.frmPrestamoCubetasJabas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmPrestamoCubetasJabas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmPrestamoCubetasJabas.setObjectName("frmPrestamoCubetasJabas")
        self.lblAlertaTituloPrestamoCubetasJabas = QtWidgets.QLabel(self.frmPrestamoCubetasJabas)
        self.lblAlertaTituloPrestamoCubetasJabas.setGeometry(QtCore.QRect(50, 40, 900, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lblAlertaTituloPrestamoCubetasJabas.setFont(font)
        self.lblAlertaTituloPrestamoCubetasJabas.setStyleSheet("color: #24D315;\n"
"background-color: rgb(255, 255, 255);")
        self.lblAlertaTituloPrestamoCubetasJabas.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAlertaTituloPrestamoCubetasJabas.setObjectName("lblAlertaTituloPrestamoCubetasJabas")
        self.btnCerrarFrmPrestamoCubetasJabas = QtWidgets.QPushButton(self.frmPrestamoCubetasJabas)
        self.btnCerrarFrmPrestamoCubetasJabas.setGeometry(QtCore.QRect(955, 10, 35, 35))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnCerrarFrmPrestamoCubetasJabas.setFont(font)
        self.btnCerrarFrmPrestamoCubetasJabas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCerrarFrmPrestamoCubetasJabas.setStyleSheet("background-color: rgb(255, 0, 4);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius: 7px;")
        self.btnCerrarFrmPrestamoCubetasJabas.setObjectName("btnCerrarFrmPrestamoCubetasJabas")
        self.txtCodigoClienteCambiarPesada = QtWidgets.QLineEdit(self.frmPrestamoCubetasJabas)
        self.txtCodigoClienteCambiarPesada.setGeometry(QtCore.QRect(50, 130, 400, 60))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.txtCodigoClienteCambiarPesada.setFont(font)
        self.txtCodigoClienteCambiarPesada.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.txtCodigoClienteCambiarPesada.setStyleSheet("border-radius: 5px;\n"
"border: 2px solid #DDD;\n"
"background-color: rgb(255, 255, 255);")
        self.txtCodigoClienteCambiarPesada.setInputMask("")
        self.txtCodigoClienteCambiarPesada.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtCodigoClienteCambiarPesada.setObjectName("txtCodigoClienteCambiarPesada")
        self.txtNombreClienteCambiarPesada = QtWidgets.QLabel(self.frmPrestamoCubetasJabas)
        self.txtNombreClienteCambiarPesada.setGeometry(QtCore.QRect(50, 130, 400, 60))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.txtNombreClienteCambiarPesada.setFont(font)
        self.txtNombreClienteCambiarPesada.setStyleSheet("color: rgb(41, 74, 117);\n"
"background-color: rgb(230, 230, 230);\n"
"padding-left: 5px;")
        self.txtNombreClienteCambiarPesada.setObjectName("txtNombreClienteCambiarPesada")
        self.lwListaClientesCambiarPesada = QtWidgets.QListWidget(self.frmPrestamoCubetasJabas)
        self.lwListaClientesCambiarPesada.setEnabled(True)
        self.lwListaClientesCambiarPesada.setGeometry(QtCore.QRect(50, 190, 400, 170))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        self.lwListaClientesCambiarPesada.setFont(font)
        self.lwListaClientesCambiarPesada.setStyleSheet("background-color: rgb(192, 192, 192);\n"
"color: rgb(255, 255, 255);")
        self.lwListaClientesCambiarPesada.setObjectName("lwListaClientesCambiarPesada")
        self.btnCambiarClientePrestamoCubetasJabas = QtWidgets.QPushButton(self.frmPrestamoCubetasJabas)
        self.btnCambiarClientePrestamoCubetasJabas.setGeometry(QtCore.QRect(570, 220, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnCambiarClientePrestamoCubetasJabas.setFont(font)
        self.btnCambiarClientePrestamoCubetasJabas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCambiarClientePrestamoCubetasJabas.setStyleSheet("QPushButton{\n"
"    background-color: #FF0000;\n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-left: 1px solid #A10F0F;\n"
"    border-right: 1px solid #A10F0F;\n"
"    border-bottom: 5px solid #A10F0F;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #FF4C4C;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #D90000;\n"
"}")
        self.btnCambiarClientePrestamoCubetasJabas.setObjectName("btnCambiarClientePrestamoCubetasJabas")
        self.btnGuardarFrmPrestamoCubetasJabas = QtWidgets.QPushButton(self.frmPrestamoCubetasJabas)
        self.btnGuardarFrmPrestamoCubetasJabas.setGeometry(QtCore.QRect(770, 220, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnGuardarFrmPrestamoCubetasJabas.setFont(font)
        self.btnGuardarFrmPrestamoCubetasJabas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGuardarFrmPrestamoCubetasJabas.setStyleSheet("QPushButton{\n"
"    background-color: #00D139;\n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-left: 1px solid #089930;\n"
"    border-right: 1px solid #089930;\n"
"    border-bottom: 5px solid #089930;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #20E355;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #14BC43;\n"
"}")
        self.btnGuardarFrmPrestamoCubetasJabas.setObjectName("btnGuardarFrmPrestamoCubetasJabas")
        self.groupBox = QtWidgets.QGroupBox(self.frmPrestamoCubetasJabas)
        self.groupBox.setGeometry(QtCore.QRect(620, 130, 331, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("border-radius: 10px;\n"
"border: 2px solid #ddd;")
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.radioBtnPrestamo = QtWidgets.QRadioButton(self.groupBox)
        self.radioBtnPrestamo.setGeometry(QtCore.QRect(30, 20, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioBtnPrestamo.setFont(font)
        self.radioBtnPrestamo.setStyleSheet("border: none;")
        self.radioBtnPrestamo.setCheckable(True)
        self.radioBtnPrestamo.setChecked(False)
        self.radioBtnPrestamo.setObjectName("radioBtnPrestamo")
        self.radioBtnDevolucion = QtWidgets.QRadioButton(self.groupBox)
        self.radioBtnDevolucion.setGeometry(QtCore.QRect(180, 20, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioBtnDevolucion.setFont(font)
        self.radioBtnDevolucion.setStyleSheet("border: none;")
        self.radioBtnDevolucion.setIconSize(QtCore.QSize(20, 20))
        self.radioBtnDevolucion.setObjectName("radioBtnDevolucion")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frmPrestamoCubetasJabas)
        self.groupBox_2.setGeometry(QtCore.QRect(50, 210, 300, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("border-radius: 10px;\n"
"border: 2px solid #ddd;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioBtnCubetas = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioBtnCubetas.setGeometry(QtCore.QRect(40, 20, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioBtnCubetas.setFont(font)
        self.radioBtnCubetas.setStyleSheet("border: none;")
        self.radioBtnCubetas.setCheckable(True)
        self.radioBtnCubetas.setChecked(False)
        self.radioBtnCubetas.setObjectName("radioBtnCubetas")
        self.radioBtnJabas = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioBtnJabas.setGeometry(QtCore.QRect(170, 20, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioBtnJabas.setFont(font)
        self.radioBtnJabas.setStyleSheet("border: none;")
        self.radioBtnJabas.setObjectName("radioBtnJabas")
        self.txtCantidadPrestamo = QtWidgets.QLineEdit(self.frmPrestamoCubetasJabas)
        self.txtCantidadPrestamo.setGeometry(QtCore.QRect(370, 210, 181, 60))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.txtCantidadPrestamo.setFont(font)
        self.txtCantidadPrestamo.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.txtCantidadPrestamo.setStyleSheet("border-radius: 5px;\n"
"border: 2px solid #DDD;\n"
"background-color: rgb(255, 255, 255);")
        self.txtCantidadPrestamo.setInputMask("")
        self.txtCantidadPrestamo.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCantidadPrestamo.setObjectName("txtCantidadPrestamo")
        self.frmTabla = QtWidgets.QFrame(self.frmPrestamoCubetasJabas)
        self.frmTabla.setGeometry(QtCore.QRect(50, 300, 900, 302))
        self.frmTabla.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid #000;")
        self.frmTabla.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmTabla.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmTabla.setObjectName("frmTabla")
        self.tblDetallePrestamo = QtWidgets.QTableWidget(self.frmTabla)
        self.tblDetallePrestamo.setGeometry(QtCore.QRect(2, 2, 896, 300))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(10)
        self.tblDetallePrestamo.setFont(font)
        self.tblDetallePrestamo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border:2px solid black;\n"
"border-left:0;\n"
"border-right:0;\n"
"border-top:0;\n"
"\n"
"")
        self.tblDetallePrestamo.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblDetallePrestamo.setTabKeyNavigation(True)
        self.tblDetallePrestamo.setProperty("showDropIndicator", False)
        self.tblDetallePrestamo.setDragDropOverwriteMode(True)
        self.tblDetallePrestamo.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tblDetallePrestamo.setObjectName("tblDetallePrestamo")
        self.tblDetallePrestamo.setColumnCount(7)
        self.tblDetallePrestamo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblDetallePrestamo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblDetallePrestamo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblDetallePrestamo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblDetallePrestamo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblDetallePrestamo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblDetallePrestamo.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDetallePrestamo.setHorizontalHeaderItem(6, item)
        self.tblDetallePrestamo.horizontalHeader().setStretchLastSection(True)
        self.tblDetallePrestamo.verticalHeader().setVisible(False)
        self.tblDetallePrestamo.verticalHeader().setCascadingSectionResizes(False)
        self.tblDetallePrestamo.verticalHeader().setHighlightSections(False)
        self.tblDetallePrestamo.verticalHeader().setSortIndicatorShown(False)
        self.tblDetallePrestamo.verticalHeader().setStretchLastSection(False)
        self.txtCantidadPrestada = QtWidgets.QLineEdit(self.frmPrestamoCubetasJabas)
        self.txtCantidadPrestada.setEnabled(False)
        self.txtCantidadPrestada.setGeometry(QtCore.QRect(460, 150, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.txtCantidadPrestada.setFont(font)
        self.txtCantidadPrestada.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.txtCantidadPrestada.setStyleSheet("border-radius: 5px;\n"
"border: 2px solid #DDD;\n"
"background-color: rgb(255, 255, 255);")
        self.txtCantidadPrestada.setInputMask("")
        self.txtCantidadPrestada.setText("")
        self.txtCantidadPrestada.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCantidadPrestada.setObjectName("txtCantidadPrestada")
        self.lblPrestamoAlCliente = QtWidgets.QLabel(self.frmPrestamoCubetasJabas)
        self.lblPrestamoAlCliente.setGeometry(QtCore.QRect(460, 120, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblPrestamoAlCliente.setFont(font)
        self.lblPrestamoAlCliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblPrestamoAlCliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPrestamoAlCliente.setObjectName("lblPrestamoAlCliente")
        self.lblAlertaTituloPrestamoCubetasJabas.raise_()
        self.btnCerrarFrmPrestamoCubetasJabas.raise_()
        self.txtNombreClienteCambiarPesada.raise_()
        self.txtCodigoClienteCambiarPesada.raise_()
        self.btnCambiarClientePrestamoCubetasJabas.raise_()
        self.btnGuardarFrmPrestamoCubetasJabas.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.txtCantidadPrestamo.raise_()
        self.frmTabla.raise_()
        self.lwListaClientesCambiarPesada.raise_()
        self.txtCantidadPrestada.raise_()
        self.lblPrestamoAlCliente.raise_()
        self.btnAbrirVentanaPrestamo = QtWidgets.QPushButton(self.centralwidget)
        self.btnAbrirVentanaPrestamo.setGeometry(QtCore.QRect(1765, 60, 150, 50))
        self.btnAbrirVentanaPrestamo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAbrirVentanaPrestamo.setStyleSheet("background-color: transparent;")
        self.btnAbrirVentanaPrestamo.setText("")
        self.btnAbrirVentanaPrestamo.setObjectName("btnAbrirVentanaPrestamo")
        self.frmAlertaUnidadDeMantenimiento = QtWidgets.QFrame(self.centralwidget)
        self.frmAlertaUnidadDeMantenimiento.setGeometry(QtCore.QRect(460, 215, 1000, 650))
        self.frmAlertaUnidadDeMantenimiento.setStyleSheet("#frmAlertaUnidadDeMantenimiento{background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-radius: 10px;\n"
"border: 2px solid #D9D9D9;}")
        self.frmAlertaUnidadDeMantenimiento.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmAlertaUnidadDeMantenimiento.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmAlertaUnidadDeMantenimiento.setObjectName("frmAlertaUnidadDeMantenimiento")
        self.lblAlertaTitulo = QtWidgets.QLabel(self.frmAlertaUnidadDeMantenimiento)
        self.lblAlertaTitulo.setGeometry(QtCore.QRect(50, 50, 900, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lblAlertaTitulo.setFont(font)
        self.lblAlertaTitulo.setStyleSheet("color: #24D315;\n"
"background-color: rgb(255, 255, 255);")
        self.lblAlertaTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAlertaTitulo.setObjectName("lblAlertaTitulo")
        self.btnCerrarFrmAlerta = QtWidgets.QPushButton(self.frmAlertaUnidadDeMantenimiento)
        self.btnCerrarFrmAlerta.setGeometry(QtCore.QRect(955, 10, 35, 35))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnCerrarFrmAlerta.setFont(font)
        self.btnCerrarFrmAlerta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCerrarFrmAlerta.setStyleSheet("background-color: rgb(255, 0, 4);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius: 7px;")
        self.btnCerrarFrmAlerta.setObjectName("btnCerrarFrmAlerta")
        self.groupBoxLedVerde = QtWidgets.QGroupBox(self.frmAlertaUnidadDeMantenimiento)
        self.groupBoxLedVerde.setGeometry(QtCore.QRect(40, 150, 300, 200))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxLedVerde.setFont(font)
        self.groupBoxLedVerde.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid #ddd;")
        self.groupBoxLedVerde.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxLedVerde.setObjectName("groupBoxLedVerde")
        self.btnOffLedVerde = QtWidgets.QPushButton(self.groupBoxLedVerde)
        self.btnOffLedVerde.setGeometry(QtCore.QRect(50, 120, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnOffLedVerde.setFont(font)
        self.btnOffLedVerde.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOffLedVerde.setStyleSheet("QPushButton{\n"
"    background-color: #FF0000;\n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-left: 1px solid #A10F0F;\n"
"    border-right: 1px solid #A10F0F;\n"
"    border-bottom: 5px solid #A10F0F;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #FF4C4C;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #D90000;\n"
"}")
        self.btnOffLedVerde.setObjectName("btnOffLedVerde")
        self.btnOnLedVerde = QtWidgets.QPushButton(self.groupBoxLedVerde)
        self.btnOnLedVerde.setGeometry(QtCore.QRect(50, 60, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnOnLedVerde.setFont(font)
        self.btnOnLedVerde.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOnLedVerde.setStyleSheet("QPushButton{\n"
"    background-color: #00D139;\n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-left: 1px solid #089930;\n"
"    border-right: 1px solid #089930;\n"
"    border-bottom: 5px solid #089930;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #20E355;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #14BC43;\n"
"}")
        self.btnOnLedVerde.setObjectName("btnOnLedVerde")
        self.groupBoxLedRojo = QtWidgets.QGroupBox(self.frmAlertaUnidadDeMantenimiento)
        self.groupBoxLedRojo.setGeometry(QtCore.QRect(350, 150, 300, 200))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxLedRojo.setFont(font)
        self.groupBoxLedRojo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid #ddd;")
        self.groupBoxLedRojo.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxLedRojo.setObjectName("groupBoxLedRojo")
        self.btnOffLedRojo = QtWidgets.QPushButton(self.groupBoxLedRojo)
        self.btnOffLedRojo.setGeometry(QtCore.QRect(50, 120, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnOffLedRojo.setFont(font)
        self.btnOffLedRojo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOffLedRojo.setStyleSheet("QPushButton{\n"
"    background-color: #FF0000;\n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-left: 1px solid #A10F0F;\n"
"    border-right: 1px solid #A10F0F;\n"
"    border-bottom: 5px solid #A10F0F;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #FF4C4C;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #D90000;\n"
"}")
        self.btnOffLedRojo.setObjectName("btnOffLedRojo")
        self.btnOnLedRojo = QtWidgets.QPushButton(self.groupBoxLedRojo)
        self.btnOnLedRojo.setGeometry(QtCore.QRect(50, 60, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnOnLedRojo.setFont(font)
        self.btnOnLedRojo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOnLedRojo.setStyleSheet("QPushButton{\n"
"    background-color: #00D139;\n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-left: 1px solid #089930;\n"
"    border-right: 1px solid #089930;\n"
"    border-bottom: 5px solid #089930;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #20E355;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #14BC43;\n"
"}")
        self.btnOnLedRojo.setObjectName("btnOnLedRojo")
        self.groupBoxBuzzer = QtWidgets.QGroupBox(self.frmAlertaUnidadDeMantenimiento)
        self.groupBoxBuzzer.setGeometry(QtCore.QRect(660, 150, 300, 200))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxBuzzer.setFont(font)
        self.groupBoxBuzzer.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid #ddd;")
        self.groupBoxBuzzer.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxBuzzer.setObjectName("groupBoxBuzzer")
        self.btnOffBuzzer = QtWidgets.QPushButton(self.groupBoxBuzzer)
        self.btnOffBuzzer.setGeometry(QtCore.QRect(50, 120, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnOffBuzzer.setFont(font)
        self.btnOffBuzzer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOffBuzzer.setStyleSheet("QPushButton{\n"
"    background-color: #FF0000;\n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-left: 1px solid #A10F0F;\n"
"    border-right: 1px solid #A10F0F;\n"
"    border-bottom: 5px solid #A10F0F;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #FF4C4C;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #D90000;\n"
"}")
        self.btnOffBuzzer.setObjectName("btnOffBuzzer")
        self.btnOnBuzzer = QtWidgets.QPushButton(self.groupBoxBuzzer)
        self.btnOnBuzzer.setGeometry(QtCore.QRect(50, 60, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnOnBuzzer.setFont(font)
        self.btnOnBuzzer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOnBuzzer.setStyleSheet("QPushButton{\n"
"    background-color: #00D139;\n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-left: 1px solid #089930;\n"
"    border-right: 1px solid #089930;\n"
"    border-bottom: 5px solid #089930;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #20E355;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #14BC43;\n"
"}")
        self.btnOnBuzzer.setObjectName("btnOnBuzzer")
        self.groupBoxOnOff = QtWidgets.QGroupBox(self.frmAlertaUnidadDeMantenimiento)
        self.groupBoxOnOff.setGeometry(QtCore.QRect(80, 400, 400, 200))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxOnOff.setFont(font)
        self.groupBoxOnOff.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid #ddd;")
        self.groupBoxOnOff.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxOnOff.setObjectName("groupBoxOnOff")
        self.btnActivaPulsoOnOff = QtWidgets.QPushButton(self.groupBoxOnOff)
        self.btnActivaPulsoOnOff.setGeometry(QtCore.QRect(50, 70, 300, 80))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnActivaPulsoOnOff.setFont(font)
        self.btnActivaPulsoOnOff.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnActivaPulsoOnOff.setStyleSheet("QPushButton {\n"
"    background-color: #0055FF;\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 3px solid #1040A2;\n"
"    border-right: 3px solid #1040A2;\n"
"    border-bottom: 8px solid #1040A2;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4683FF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0649D1;\n"
"}")
        self.btnActivaPulsoOnOff.setObjectName("btnActivaPulsoOnOff")
        self.groupBoxZero = QtWidgets.QGroupBox(self.frmAlertaUnidadDeMantenimiento)
        self.groupBoxZero.setGeometry(QtCore.QRect(520, 400, 400, 200))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxZero.setFont(font)
        self.groupBoxZero.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid #ddd;")
        self.groupBoxZero.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxZero.setObjectName("groupBoxZero")
        self.btnActivaPulsoZero = QtWidgets.QPushButton(self.groupBoxZero)
        self.btnActivaPulsoZero.setGeometry(QtCore.QRect(50, 70, 300, 80))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnActivaPulsoZero.setFont(font)
        self.btnActivaPulsoZero.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnActivaPulsoZero.setStyleSheet("QPushButton {\n"
"    background-color: #0055FF;\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    border-left: 3px solid #1040A2;\n"
"    border-right: 3px solid #1040A2;\n"
"    border-bottom: 8px solid #1040A2;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4683FF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0649D1;\n"
"}")
        self.btnActivaPulsoZero.setObjectName("btnActivaPulsoZero")
        self.frmAlerta = QtWidgets.QFrame(self.centralwidget)
        self.frmAlerta.setGeometry(QtCore.QRect(1440, 10, 470, 80))
        self.frmAlerta.setStyleSheet("background-color: rgb(0, 190, 0);\n"
"color: rgb(255, 255, 255);")
        self.frmAlerta.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmAlerta.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmAlerta.setObjectName("frmAlerta")
        self.lblAlerta = QtWidgets.QLabel(self.frmAlerta)
        self.lblAlerta.setGeometry(QtCore.QRect(1, 9, 471, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.lblAlerta.setFont(font)
        self.lblAlerta.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAlerta.setObjectName("lblAlerta")
        self.imgPrestamo = QtWidgets.QLabel(self.centralwidget)
        self.imgPrestamo.setGeometry(QtCore.QRect(1775, 67, 30, 30))
        self.imgPrestamo.setStyleSheet("background-color: transparent;")
        self.imgPrestamo.setText("")
        self.imgPrestamo.setScaledContents(True)
        self.imgPrestamo.setObjectName("imgPrestamo")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1765, 60, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    background-color: #00D139;\n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-left: 1px solid #089930;\n"
"    border-right: 1px solid #089930;\n"
"    border-bottom: 5px solid #089930;\n"
"    padding: 5px\n"
"}\n"
"QLabel:hover{\n"
"    background-color: #20E355;\n"
"}")
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.imgFondo.raise_()
        self.label_2.raise_()
        self.imgPrestamo.raise_()
        self.btnAbrirVentanaPrestamo.raise_()
        self.lblTituloPrincipal.raise_()
        self.imgVentaBeneficiado.raise_()
        self.lblVenta.raise_()
        self.lblSubTituloPrincipal.raise_()
        self.lblmimizar.raise_()
        self.lblcerrar.raise_()
        self.btnminimizar.raise_()
        self.btnCerrar.raise_()
        self.imgVentaVivo.raise_()
        self.lblVenta_2.raise_()
        self.img_unidad_mantenimiento.raise_()
        self.btnUnidadMantenimiento.raise_()
        self.frmSombra.raise_()
        self.frmIngresarPassword.raise_()
        self.frmAlertaUnidadDeMantenimiento.raise_()
        self.frmPrestamoCubetasJabas.raise_()
        self.frmAlerta.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblTituloPrincipal.setText(_translate("MainWindow", "SISTEMA INTEGRADO DE VENTA \n"
" BRIALEMAGI S.A.C."))
        self.lblVenta.setText(_translate("MainWindow", "VENTA \n"
" BENEFICIADO"))
        self.lblSubTituloPrincipal.setText(_translate("MainWindow", "PRESIONE ENTER PARA INICIAR :"))
        self.lblVenta_2.setText(_translate("MainWindow", "VENTA VIVO"))
        self.lblTextoUnidadMantenimiento.setText(_translate("MainWindow", "Debe escribir contraseña para ingresar \n"
" a la Unidad de Mantenimiento"))
        self.txtPasswordUnidadMantenimiento.setPlaceholderText(_translate("MainWindow", "*******"))
        self.btnAceptarFrmIngresarPassword.setText(_translate("MainWindow", "Aceptar (↵)"))
        self.btnCancelarFrmIngresarPassword.setText(_translate("MainWindow", "Cancelar (-)"))
        self.lblAlertaTituloPrestamoCubetasJabas.setText(_translate("MainWindow", "Préstamo de Cubetas y Jabas"))
        self.btnCerrarFrmPrestamoCubetasJabas.setText(_translate("MainWindow", "X"))
        self.txtCodigoClienteCambiarPesada.setText(_translate("MainWindow", "Edinson"))
        self.txtCodigoClienteCambiarPesada.setPlaceholderText(_translate("MainWindow", "  Buscar Cliente"))
        self.txtNombreClienteCambiarPesada.setText(_translate("MainWindow", "Nombre"))
        self.btnCambiarClientePrestamoCubetasJabas.setText(_translate("MainWindow", "Cambiar\n"
"Cliente (+)"))
        self.btnGuardarFrmPrestamoCubetasJabas.setText(_translate("MainWindow", "Guardar"))
        self.radioBtnPrestamo.setText(_translate("MainWindow", "Préstamo"))
        self.radioBtnDevolucion.setText(_translate("MainWindow", "Devolución"))
        self.radioBtnCubetas.setText(_translate("MainWindow", "Cubetas"))
        self.radioBtnJabas.setText(_translate("MainWindow", "Jabas"))
        self.txtCantidadPrestamo.setText(_translate("MainWindow", "0"))
        self.txtCantidadPrestamo.setPlaceholderText(_translate("MainWindow", "Cantidad"))
        item = self.tblDetallePrestamo.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "N°"))
        item = self.tblDetallePrestamo.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cliente"))
        item = self.tblDetallePrestamo.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tipo"))
        item = self.tblDetallePrestamo.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Variedad"))
        item = self.tblDetallePrestamo.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cantidad"))
        item = self.tblDetallePrestamo.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Hora"))
        item = self.tblDetallePrestamo.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "ID Pesada"))
        self.txtCantidadPrestada.setPlaceholderText(_translate("MainWindow", "0"))
        self.lblPrestamoAlCliente.setText(_translate("MainWindow", "Préstamo al Cliente"))
        self.lblAlertaTitulo.setText(_translate("MainWindow", "¡Unidad de Mantenimiento!"))
        self.btnCerrarFrmAlerta.setText(_translate("MainWindow", "X"))
        self.groupBoxLedVerde.setTitle(_translate("MainWindow", "LED VERDE"))
        self.btnOffLedVerde.setText(_translate("MainWindow", "OFF"))
        self.btnOnLedVerde.setText(_translate("MainWindow", "ON"))
        self.groupBoxLedRojo.setTitle(_translate("MainWindow", "LED ROJO"))
        self.btnOffLedRojo.setText(_translate("MainWindow", "OFF"))
        self.btnOnLedRojo.setText(_translate("MainWindow", "ON"))
        self.groupBoxBuzzer.setTitle(_translate("MainWindow", "BUZZER"))
        self.btnOffBuzzer.setText(_translate("MainWindow", "OFF"))
        self.btnOnBuzzer.setText(_translate("MainWindow", "ON"))
        self.groupBoxOnOff.setTitle(_translate("MainWindow", "PULSO ON/OFF"))
        self.btnActivaPulsoOnOff.setText(_translate("MainWindow", "ACTIVAR"))
        self.groupBoxZero.setTitle(_translate("MainWindow", "PULSO ZERO"))
        self.btnActivaPulsoZero.setText(_translate("MainWindow", "ACTIVAR"))
        self.lblAlerta.setText(_translate("MainWindow", "Prestamo guardado correctamente"))
        self.label_2.setText(_translate("MainWindow", "PRÉSTAMO"))
